require "capistrano/setup"

require "capistrano/rbenv"

require "capistrano/inaminute/plugin"
install_plugin Capistrano::Inaminute::Plugin

Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
